### ISSUE TITLE
Match CAN config with CAN network settings (500 Kbaud)

### ISSUE THREAD

**Issue by alexnewman23** [alexnewman23/DFR_CVC#11]

**Comment by leina05** [comment]
Fixed, CAN settings configured properly and we are able to snoop vehicle CAN bus. Required fixing system clock configuration, PLLM set to 25 but needed to be 8 (to match frequency of external crystal). 

CAN baud rate calculation:
- CAN runs on APB1, with a divider of 4. So CAN clock frequency = 216 MHz / 4 = 54 MHz.
- CAN baud rate = (Fclk / prescaler) / (1 + BTS_1 + BTS_2)

where (1 + BTS_1 + BTS_2) is the number of time quantiles.
