### ISSUE TITLE
Implement SD communication (read and write) in free rtos

### ISSUE THREAD

**Issue by alexnewman23** [alexnewman23/DFR_CVC#13]

**Comment by leina05** [comment]
Working on passing Elm Chan sd driver test in freertos task. having issue with multi-sector write due to pbuff memory access... triggering HardFault 

Possible solutions:
- use global buffer
- declare buffer in test_diskio function instead of passing into function

**Comment by leina05** [comment]
Solved multiple sector write bug!!
- changed buff to static global variable
- was running into issues with vTaskSuspend, turned out sprintf was the cause (sprintf is NOT thread safe!!)

Going to test with different variations of buff location (in function), updates to come

**Comment by leina05** [comment]
Tried it with buff inside test function... DOES NOT WORK, Hard fault. Would be good to talk to John about potential reasons for this. Seems to suggest that using task stack to hold read/write buffer for FAT doesn't work...
