### ISSUE TITLE
Event-triggered SPI_routine_task

### ISSUE THREAD

**Issue by alexnewman23** [alexnewman23/DFR_CVC#18]
Having trouble implementing xQueueSendfromISR() in order to wake up the SPI_routine_task. Leina checked the function of the CAN demo which also uses xQueueSendfromISR() and the demo functions well. Need to look into the differences in implementation of the CAN and SPI versions in order to get to bottom of problem

**Comment by leina05** [comment]
Pretty sure that the SPI routine is too time-sensitive to break up using queues. It seems that the frequency of the SPI interrupts prevent the task from ever waking up even after the call to xQueueSendfromISR(). Tried using taskENTER_CRITICAL after xQueueReceive, still didn't work. 

Best thing is probably to use semaphores to protect SPI input/output vectors. The task that kicks off the SPI transmission can take the semaphore before doing so, then wait for an event/message that signals the end of the SPI transmission and give the semaphore back.
